### ISSUE TITLE
Search attendee's 

### ISSUE THREAD

**Issue by Biztactix-Ryan** [jamesmontemagno/MeetupManager#20]
G'day...  I've only played with Xamarin...  So I don't think I can tackle this...  But we regularly see 100+ and new years was 385 registered.... 

So we need to be able to search attendee's to check them in...  We may have ten Steve's so nice big pictures will help too... 

Thanks in advance if you tackle this....  Otherwise I'll open up the guts when I can

Regards
Ryan

**Comment by jamesmontemagno** [comment]
Implemented
