### ISSUE TITLE
Using it in new Xamarin

### ISSUE THREAD

**Issue by pramadiputra** [jamesmontemagno/MeetupManager#21]
Mr. James Montemagno / Principal Manager of Xamarin, 

Can I use these with the latest Xamarin and Xamarin Studio And Or Xamarin for Visual Studio ? 
Haven't try it, I'm new to Xamarin and in learning and developing Xamarin.Forms :) 

Thanks :)

**Comment by jamesmontemagno** [comment]
You should be able to with some additional setup code, I haven't built it in a bit, but should be fine.
