### ISSUE TITLE
looking for version 1 MVVMCross code

### ISSUE THREAD

**Issue by mdonogma** [jamesmontemagno/MeetupManager#22]
Hi James,

Love your work.

I'm battling to get OAuth login working with MVVMCross.

Using Xamarin forms + MVVMCross Forms & hoping your meetup manager MVVMCross version can shed some light on the issue i'm having.

**Comment by mdonogma** [comment]
here is the source project i've used to convert to MVVMCross forms.
https://github.com/DamianMehers/XamFormsUWPOAuth

**Comment by jamesmontemagno** [comment]
Right around here: https://github.com/jamesmontemagno/MeetupManager/commit/3cc4c2b47299de220d07df7336b052cb9ab84ca0

**Comment by mdonogma** [comment]
Thanks so much, it help me solve the problem in no time.

Keep up the great work.

PS, working through xamarin university live classes and the trainers & content rock.
________________________________
