### ISSUE TITLE
In case of google "disallowed_useragent" error is thrown.

### ISSUE THREAD

**Issue by ramanjit-netsol** [jamesmontemagno/MeetupManager#24]
In case of google "disallowed_useragent" error is thrown. Please let me know how to resolve these

**Comment by jamesmontemagno** [comment]
are you talking about the versions on the app store or this sample?

**Comment by ramanjit-netsol** [comment]
Yes provide a working code sample for google login in meetup.

**Comment by jamesmontemagno** [comment]
Google now blocks webviews and you have to use chrome custom tabs, in this instance would needed a newer version of Xamarin.Auth.

See: https://github.com/xamarin/Xamarin.Auth

**Comment by ramanjit-netsol** [comment]
I have used chrome custom tabs also but in my case when i try to specify a custom redirect url and define the applinks for it. The CustomUrlSchemeInterceptorActivity intercepts the link the first time also when the meetup login page is opening. It filters the redirect url and the close the login page. Therefore the meetup login page is not opening up. If I defime a http url for the redirect url the meetup login page in the chrome custom tabs does not close after authentication.
