### ISSUE TITLE
In case of google "disallowed_useragent" error is thrown.

### ISSUE THREAD

**Issue by ramanjit-netsol** [jamesmontemagno/MeetupManager#25]
This is with reference to 
https://github.com/jamesmontemagno/MeetupManager/issues/24

I have used chrome custom tabs also but in my case when i try to specify a custom redirect url and define the applinks for it. The CustomUrlSchemeInterceptorActivity intercepts the link the first time also when the meetup login page is opening. It filters the redirect url and the close the login page. Therefore the meetup login page is not opening up. If I defime a http url for the redirect url the meetup login page in the chrome custom tabs does not close after authentication.

**Comment by jamesmontemagno** [comment]
I would post an issue on the Xamarin.Auth for help there.
